// Teacher narrative content: Phase 4, Phase 5, Phase 6.1, Phase 6.2
module.exports = [
{
  id: "lab04",
  duration: "90 minutes",
  prerequisites: "Phase 3 completed and validated.",
  opening: "This session has the highest bug density of the early course — three real, distinct failures in one install. Tell students up front that today is genuinely about debugging practice, more than any other session so far, and that patience is the actual skill being taught.",
  concept: "Explain Quadlet as \"describe a container the way you'd describe a systemd service, and let Podman generate the real unit for you.\" Draw the reverse-proxy chain on the board: browser to Caddy to Open WebUI (loopback only) to Ollama (native, on the host). Emphasize why Open WebUI never talks to the browser directly — Caddy is the only thing meant to be LAN/public-facing.",
  designDecisions: "The /data/rag versus Open WebUI's own app-state volume distinction is subtle but important: only files uploaded THROUGH the UI are part of Open WebUI's own RAG database record. A script that drops a file directly into /data/rag does not automatically become part of RAG, because there's no database record for it. This is worth a concrete demonstration if time allows.",
  runningTheLab: "Have students run the validation script even if the install appears to succeed — 'appears to succeed' and 'actually validated' are different claims throughout this whole course, and this lab is a particularly good place to reinforce that since the first two bugs below don't surface until you actually try to USE the deployed services, not just install them.",
  gotchaStory: "Walk through all three bugs as a single narrative, in the order they were actually discovered — the sequencing itself is the lesson. Bug one: the Quadlet config file used an 'AddHost=' key to let the container reach the host — a key that simply doesn't exist in the specific Podman version Ubuntu 24.04 ships. Ask: how would you even discover this, versus just seeing a generic error? (Answer: the actual error names the unsupported key directly — read errors literally before assuming something more exotic.) The fix used a generic pass-through key (PodmanArgs=) that works regardless of which specific keys a given Podman version supports — a more version-tolerant design than hardcoding to what happened to be available. Bug two, discovered immediately after fixing bug one: 'systemctl enable' failed with 'is transient or generated.' This is a genuinely non-obvious distinction — Quadlet-generated units are NOT meant to be enabled the normal way; they're already wired for boot via their own file's [Install] section, and you just start them. Bug three, discovered only once the first two were fixed and Caddy actually tried to run: 'bind: permission denied' on port 80, because rootless containers can't bind privileged ports without a system-wide policy change. Rather than loosen a system-wide security setting for one service's convenience, the fix moved Caddy to port 8000. Ask students to articulate why that's the better tradeoff, not just the easier one.",
  discussion: [
    { q: "Why does version drift between what a script assumes and what's actually installed cause exactly this class of bug?", note: "Connect to Phase 1's librtlsdr0/librtlsdr2 story — this is the SAME class of failure (assumed-versus-actual version) showing up again in a completely different layer of the stack." },
    { q: "What's the real security tradeoff between lowering the unprivileged-port sysctl versus just moving your service to a higher port?", note: "Push toward: the sysctl change is system-wide and affects every future process, while moving one service's port is scoped and reversible." },
    { q: "How would you design a Quadlet file to be more version-tolerant from the start?", note: "Good answers reach for the generic pass-through pattern (PodmanArgs) proactively rather than only after hitting the specific error." }
  ],
  wrapUp: "Tell students Phase 5 shifts from infrastructure plumbing to the actual AI ingest pipeline — and that it includes a genuinely fascinating hardware-compatibility bug involving mismatched CUDA versions on brand-new GPU hardware."
},
{
  id: "lab05",
  duration: "75 minutes",
  prerequisites: "Phase 4 completed and validated.",
  opening: "Bring a real, varied set of test files if possible — a PDF, a scanned image, a short audio clip — and let students watch each one get processed live, rather than describing the pipeline in the abstract.",
  concept: "Frame this pipeline's three input types (documents, images, audio) as three genuinely different AI problems solved by three different tools chained together (Docling, OCR, faster-whisper), unified only by writing to the same output corpus. This is a good moment to discuss why no single model handles all three well.",
  designDecisions: "Idempotency via content-hash manifest is worth a concrete walkthrough: what EXACTLY changes in the manifest database when you run ingest twice against the same unchanged file? Have students predict the answer before showing them.",
  runningTheLab: "After the validation script passes, have students deliberately delete one processed output file directly (not through any pipeline tool) and re-run ingest. This sets up the gotcha story below as something they've just experienced firsthand, not just heard about.",
  gotchaStory: "Two bugs here, and the second one connects directly to what students just did in the lab. Bug one is a genuine hardware-compatibility trap: on cutting-edge GPU hardware reporting CUDA 13, the speech-to-text backend (ctranslate2) failed with a missing library error — because its published packages hadn't caught up to CUDA 13 yet, and specifically needed a CUDA 12 library, even though the rest of the system was CUDA 13. The fix installed the older CUDA 12 libraries ALONGSIDE the CUDA 13 stack, as separate files with no conflict — a good example of 'newer hardware can create MORE compatibility problems, not fewer.' Bug two is the one your students just walked into during the lab: if you delete a processed output file directly, does the ingest pipeline notice and reprocess it, or does it trust its own database record and skip the file forever? On the real build, it originally trusted the database blindly — a real bug, since the manifest and the actual filesystem can desync any time something outside the pipeline's control touches its output. The fix made the idempotency check verify BOTH the database record AND that the claimed output file still physically exists. Ask: what just happened when YOU deleted a file and re-ran ingest? Did it notice?",
  discussion: [
    { q: "Why can very new hardware/drivers actually cause MORE compatibility problems than older, more established combinations?", note: "Look for the observation that library ecosystems (like ctranslate2) lag behind hardware/driver releases, especially for anything GPU-specific." },
    { q: "What's the risk of trusting a library's documented 'graceful fallback' behavior without testing it yourself?", note: "Reference the related bug where a code comment claimed automatic CPU fallback that a real test proved false — documentation and reality can diverge." },
    { q: "How would you design a manifest system to be resilient against a file disappearing outside the pipeline's own control?", note: "The answer they should reach independently: check the claimed output's actual existence, not just a database flag." }
  ],
  wrapUp: "Preview Phase 6.1 as the pivot point of the whole course — the AI infrastructure is essentially complete, and everything from here forward is SIGINT-specific. Note that this next lab requires the RX-888 hardware specifically, and remind students who lack it to pair up or follow along conceptually."
},
{
  id: "lab06",
  duration: "90 minutes (or conceptual walkthrough for students without RX-888 hardware)",
  prerequisites: "RX-888 MkII hardware; Phase 1's rx888 device option selected and validated.",
  opening: "This is the architectural centerpiece of the whole SIGINT half of the course. Open by asking: \"If you wanted to monitor the ENTIRE HF spectrum simultaneously, not just one frequency at a time, what would that even require?\" Let students struggle with the question before introducing radiod as the answer.",
  concept: "The wideband-capture-plus-many-simultaneous-channels architecture is genuinely unusual and worth slowing down for. No other tool in this build's stack does this — OpenWebRX+, GNU Radio flowgraphs elsewhere in the course, none of them capture everything at once and channelize it live. Make sure students understand this BEFORE the \"why not OpenWebRX+\" discussion, or that discussion won't land.",
  designDecisions: "The decision NOT to route RX-888 through OpenWebRX+ is one of the most important architectural choices in the whole course, and it was made deliberately, more than once, across the actual build. Frame it as choosing a tool for its ARCHITECTURE, not its feature checklist — OpenWebRX+ could technically support the RX-888 via an optional connector, but its whole design center is serving a browser UI to a few live users, not publishing many independent channels for arbitrary downstream automated consumption the way this build's later phases (SigMF export, occupancy tracking) need.",
  runningTheLab: "If any students lack RX-888 hardware, pair them with someone who has it rather than leaving them to just watch slides — have the non-hardware student drive the terminal while the hardware owner handles physical setup, so everyone gets real command-line practice even without owning the device.",
  gotchaStory: "This bug is a genuinely elegant lesson in why testing AS the right user matters, not just testing as SOME user. Phase 1, several weeks ago, validated RX-888 USB access — but it did so running as the interactive human user's own account. radiod, however, runs as its own dedicated 'radio' system user, created fresh by its own install process — a completely different account with no inherent relationship to the human user's permissions. Phase 1 passing proved NOTHING about whether 'radio' could access the USB device, because it never actually tried, as that user. The fix has the install script inspect the real udev rule and explicitly add the 'radio' user to whatever group grants access, rather than assuming a passing Phase 1 result automatically covers a completely different user context in Phase 6.1. Ask students: can you think of another place in this build, or in any system you've worked on, where 'it worked when I tested it' quietly meant 'it worked for the user I happened to be logged in as' rather than the user that actually needed it to work?",
  discussion: [
    { q: "What other services in a typical Linux deployment run as their own dedicated system user, and why does that pattern exist?", note: "Web servers, databases, and mail servers are common examples — the underlying reason is limiting the blast radius of a compromise to that service's own narrow permissions." },
    { q: "Why is 'many simultaneous channels from one capture' architecturally different from 'many separate captures,' and what does that cost in hardware/DSP terms?", note: "Steer toward the DSP concept of channelizing a wideband capture (filtering out many narrow channels from one wide sample stream) versus running many independent, redundant narrowband captures." },
    { q: "If you had to add a NEW downstream consumer of radiod's multicast streams, what would you need to know before writing it?", note: "Good answers reference needing to know the multicast group addresses/ports for the specific channel of interest, and the data format being published on that channel." }
  ],
  wrapUp: "Tell students Phase 6.2 is a shorter, more mechanical session by comparison — installing GNU Radio and decode tools — but that it sets up a Python environment decision made all the way back in Phase 2 to finally pay off."
},
{
  id: "lab07",
  duration: "60 minutes",
  prerequisites: "Phase 6.1 completed (or skipped if no RX-888) and Phase 2's venv understanding fresh.",
  opening: "Open by asking students to recall the venv-isolation decision from Phase 2, several weeks back. If they can't recall it unprompted, that's useful information — it tells you this session needs a fuller recap before the new material lands.",
  concept: "GNU Radio, gr-osmosdr, direwolf, and multimon-ng are four different tools solving four different pieces of the 'decode what the SDR receives' problem. Keep the distinction clear: GNU Radio is the general DSP framework, the others are specific digital-mode decoders it can be paired with or that stand alongside it.",
  designDecisions: "The system-Python-versus-venv boundary is the intellectual payoff of this session, and it should feel like a callback, not new information delivered cold. Say explicitly: \"Remember Phase 2's decision not to use --system-site-packages in either venv? This is why. GNU Radio's Python bindings only exist in system dist-packages, installed by its own apt package — neither venv can see them, by design, and that's fine, because GNU Radio flowgraphs are meant to run under system Python anyway.\"",
  runningTheLab: "Make the validation script's actual mechanism visible to students — point out that it builds and runs a REAL flowgraph (a genuine source-to-sink data path), not just checking that a package installed. Ask them why that distinction matters before revealing the answer.",
  gotchaStory: "There isn't a dramatic bug story for this session specifically — use the time instead to make the validation methodology itself the teaching point. Ask: \"If 'apt install gnuradio' completes with no errors, do you actually know GNU Radio works?\" Walk through everything that could still be broken despite a clean install: Python bindings not actually importable, gr-osmosdr not finding SDR hardware correctly, a Qt/VOLK/Boost dependency conflict nobody's apt dependency resolver caught. The only way to actually know is to build and run something real — which is exactly what this phase's validation script does, and exactly the same principle Phase 1 applied to hardware. Make the through-line explicit: 'prove it with a real test, not an installation success message' has now been true for hardware (Phase 1) AND software (this phase), and it will be true again for every remaining phase in the course.",
  discussion: [
    { q: "Why might 'the package installed' and 'the software actually works' be two very different claims, especially for a large DSP framework?", note: "Large frameworks with many optional dependencies (Qt, VOLK, Boost) have many places a working INSTALL can still leave a broken RUNTIME." },
    { q: "What are the tradeoffs of the venv-isolation decision made in Phase 2, now that we see its consequence here?", note: "The tradeoff: you gain guaranteed dependency isolation between the two Python domains, at the cost of GNU Radio flowgraphs needing to live in a third, separate Python context." },
    { q: "Could you restructure this build to avoid the system-Python/venv split entirely? What would you give up?", note: "You could use --system-site-packages on a venv to see GNU Radio's bindings, but you'd risk exactly the dependency conflicts the isolation was designed to prevent." }
  ],
  wrapUp: "Preview Phase 6.3 as a change of pace — no hardware, no drivers, just a live sync against an external reference wiki. Warn students it includes a satisfying rate-limiting bug story."
}
];
