// Teacher narrative content: Final Lab (Use Cases)
module.exports = [
{
  id: "lab12",
  duration: "Full session, 120+ minutes recommended — this is a culminating lab, not a standard-length session",
  prerequisites: "All prior lab sessions completed to whatever extent each student's hardware allowed.",
  opening: "Open not with new material, but by asking students to describe, unprompted, the full path a signal takes through the system they've built across the semester — antenna to hardware to decode to database to AI query. Let there be gaps and hesitation; those gaps tell you exactly what to reinforce today. This is a synthesis session, and the best opening exposes what students genuinely retained versus what needs a second pass.",
  concept: "Walk through each example use case as a real composition of specific prior labs, naming them explicitly: spectrum situational awareness draws on Phase 6.6's occupancy database plus Phase 3's local LLM, now joined by the native tool that lets the model QUERY the DB live (the capture->DB->AI loop is closed, not aspirational); the signal-identification workflow draws on the vision model describing a waterfall's shape, the SigID reference tool (Phase 6.3's mirror, now queryable live) supplying candidate characteristics, and the student's own measured frequency/bandwidth confirming — a three-way triangulation, and note it requires SWITCHING models because gemma3:12b sees images but can't call tools while qwen3:14b calls tools but can't see images; the WiFi-device use case draws on Kismet via its own native tool (a different KIND of intelligence — device presence, not frequency occupancy); the physical-security/asset-discovery use case is a callback to hardware (Ubertooth, Evil Crow RF) set up in Phase 1 but not yet wired into the AI layer. Naming the specific dependencies — and which are live versus still future — is what makes this feel like honest synthesis rather than a new topic.",
  designDecisions: "This is the session to make the 'sovereign versus merely local' distinction land with full force, now that students have built every piece themselves. Ask directly: at query time, right now, on the system you built, does ANY use case we've discussed today require an outbound internet connection to function? The honest answer is no — and that's worth sitting with, given how unusual that property is for a modern AI-assisted tool.",
  runningTheLab: "Give students real choice in which use case they reproduce end-to-end — the diversity of choices across the class is itself valuable material for the group discussion at the end. Actively encourage students with different available hardware to choose different use cases suited to what they actually have, rather than all attempting the same one.",
  gotchaStory: "There is no single new bug story for this session — instead, use this time for a genuine retrospective across the whole semester. Ask students to name, from memory, as many of the real bugs from prior sessions as they can recall (the librtlsdr0 rename, the FFTW non-bug, the OLLAMA_HOST/permissions cascade, the three Quadlet bugs, the CUDA mismatch, the rate-limiting fix, the OpenWebRX+ gain/aprs_symbols bugs, the SigMF metadata guess, the suspiciously-identical calibration readings). The fact that they likely CAN recall several of these, in detail, months later, is itself the evidence that teaching through real failure narratives works better than teaching through idealized happy-path instructions. Make this observation explicit to the class — it's a good moment of metacognition about how the course itself was taught, not just what it taught.",
  discussion: [
    { q: "Which single phase of this build do you think has the most direct application to your own professional or research context?", note: "There's no wrong answer here — use it to surface how differently students in a mixed cybersecurity/engineering/hobbyist cohort will value different phases." },
    { q: "Where would you draw the line between 'local by default' and 'cloud by exception' if you were deploying this in a real organization?", note: "Push for a SPECIFIC policy, not a vague preference — what data classification would trigger permission to use a cloud escalation, and who approves it?" },
    { q: "What SIGINT use case would you want to pursue that this course's current architecture does NOT yet support?", note: "This question is deliberately a bridge into the final project — capture answers carefully, since they may directly shape what you assign." }
  ],
  wrapUp: "Close the course-proper by introducing the final project at a high level (design specifics still TBD at time of writing), framed explicitly as building on this semester's foundation rather than starting anything from scratch. Tell students the project should extend, not replace, what they've already built and validated across twelve lab sessions."
}
];
