// Teacher narrative content: Phase 6.3, 6.4, 6.5, 6.6
module.exports = [
{
  id: "lab08",
  duration: "45 minutes active + a long background sync (30-50+ minutes) students should start early and let run",
  prerequisites: "Phase 6.2 completed; internet access to sigidwiki.com.",
  opening: "Start the sync running in the FIRST five minutes of class, before you explain anything about it — students will have a real, live, multi-hour process to observe by the time you're done with the concept discussion, rather than a purely abstract description.",
  concept: "Explain why this reference catalog is mirrored LOCALLY rather than queried live at analysis time — tie it directly back to the course's sovereign-AI framing from Lab 0. Ask: what would it mean for signal-identification queries to depend on a live internet connection to a third-party wiki, in exactly the deployment contexts this course cares about?",
  designDecisions: "The incremental-sync design (bootstrap once, then only changed pages afterward) mirrors the idempotent-manifest pattern from Phase 5's ingest pipeline — point out the parallel explicitly. It reinforces that this is a recurring design pattern in the build, not a one-off.",
  runningTheLab: "Since the sync takes a long time, use this session's extra time for something that doesn't need to wait on it — this is a good session to let students explore the SigID mirror's actual content (once enough of it has synced) or read ahead into Phase 6.4's material.",
  gotchaStory: "This is a genuinely satisfying story about the difference between a fatal error and a recoverable one. On the real build's first bootstrap sync — hundreds of pages, many with image downloads — the external wiki's server, partway through, started returning HTTP 429 (Too Many Requests). The ORIGINAL code treated any non-success response as fatal, aborting the ENTIRE multi-hour sync and losing everything not yet saved. Ask students: is a rate-limit response, across a run making hundreds of API calls, actually an exceptional failure, or an expected condition you should have planned for from the start? The fix added retry-with-backoff, honoring the server's own Retry-After header, applied consistently across BOTH the metadata calls and a separate, previously-unprotected file-download code path — a second related bug found only by asking 'does this same fix need to apply anywhere else?' rather than stopping at the first fix. The re-run after both fixes completed cleanly: 497 pages, 834 files, with dozens of 429 responses all handled gracefully instead of fatally. This is a good moment to discuss designing for expected failure modes versus treating every non-happy-path response as exceptional.",
  discussion: [
    { q: "Why should a rate-limit response be treated differently from most other HTTP error codes?", note: "A 429 tells you explicitly that retrying LATER will likely succeed — unlike, say, a 404, which retrying will never fix." },
    { q: "What's the ethical dimension of scraping/mirroring a public wiki's content — what did this build do to be a 'good citizen' of that infrastructure?", note: "Rate-limiting requests deliberately, using an honest identifiable User-Agent, and syncing incrementally rather than repeatedly re-downloading everything are all real, concrete answers here." },
    { q: "If this sync needed to run against ten different wikis with ten different rate-limit policies, how would you generalize the retry logic?", note: "Look for answers involving configurable backoff parameters per source, rather than one hardcoded policy assumed to fit everything." }
  ],
  wrapUp: "Preview Phase 6.4 as the session where the whole system becomes visually satisfying — a real browser-based waterfall and radio receiver — and warn students it includes two non-obvious bugs that both LOOK like something else entirely at first."
},
{
  id: "lab09",
  duration: "90 minutes",
  prerequisites: "Phase 6.2 and 6.3 completed; HackRF and/or RTL-SDR hardware with an antenna.",
  opening: "This is usually the most engaging session of the semester for students — a real, live, browser-based radio receiver. Let them explore the waterfall freely for a few minutes before imposing any structure on the session; some organic discovery here pays off in engagement for the rest of the lab.",
  concept: "Introduce the Feature Report (http://<host>:8073/features) as a genuinely well-designed piece of software — a self-diagnosing tool that states, for every optional capability, exactly why it is or isn't available. Make the point that most software does NOT do this well, and that checking documentation like this BEFORE debugging blind from symptoms is a real professional habit worth building now.",
  designDecisions: "Explain the deliberate ordering: Phase 6.2's decode tools had to be installed BEFORE OpenWebRX+, so its own auto-detection at first startup correctly finds direwolf and multimon-ng already present. This is a good moment to discuss install-order dependencies generally, and why they're easy to get backwards without documentation forcing the correct sequence.",
  runningTheLab: "Budget real time for gain tuning — this is where students will spend the most frustrated minutes if you don't preempt it with the gotcha story below FIRST, before they hit the problem themselves. Consider telling the gain story before the lab steps this time, rather than after, so students recognize the symptom immediately rather than spending 20 minutes confused.",
  gotchaStory: "Two real bugs here, both worth their own full telling. Bug one: on the actual build, a real, live antenna produced a waterfall with faint, indistinguishable signals — genuinely confusing, because the antenna WAS working and a signal WAS present. The actual cause had nothing to do with the antenna, frequency, or hardware: RF gain lives specifically in the per-profile Settings page, NOT the live receiver panel's own Gain control, which visually looks like it should work but doesn't actually persist. Tell students this explicitly before they hit it themselves, or budget extra patience if you let them discover it. Bug two is a genuinely subtle lesson about reading a diagnostic tool CAREFULLY, not just at a glance: Packet/APRS mode was missing from the digital-mode list, even though the Feature Report showed direwolf itself as fully available (YES). The actual gating dependency, only visible by reading every line of that feature's Feature Report entry rather than stopping at the first YES, was a SECOND, unrelated requirement — aprs_symbols, a package of map icon assets, which showed NO, and which wasn't even distributed through the normal package repository, requiring a direct git clone install instead. Ask students: what's the general lesson about assuming ONE green checkmark means an entire feature is ready?",
  discussion: [
    { q: "Why is checking a documented Feature Report more reliable than guessing from a live UI's symptoms?", note: "A documented report states the ACTUAL missing dependency directly, where guessing from symptoms (faint signal, missing mode) could point toward many wrong hypotheses first." },
    { q: "What's the difference between a device not having enough gain versus a device not being properly connected — how would you tell them apart faster next time?", note: "A properly connected antenna with insufficient gain typically shows SOME signal, just weak/indistinguishable; a disconnected antenna typically shows pure noise with no structure at all." },
    { q: "Should a feature-flag system report ALL of a feature's unmet dependencies at once, or just the first one it finds? What are the tradeoffs?", note: "Reporting all of them (as this Feature Report actually does) is more useful but requires more design work up front than a simple pass/fail check." }
  ],
  wrapUp: "Preview Phase 6.5 as a shift from 'live and visual' back to 'file formats and standards' — exporting raw captures in a format other tools outside this build can actually use."
},
{
  id: "lab10",
  duration: "75 minutes",
  prerequisites: "Phase 6.4 completed; at least one SDR device for a real capture.",
  opening: "Ask students directly: \"Of everything we've built so far — radiod, OpenWebRX+ — which of them can actually save you the RAW signal, not just what it decoded?\" Let them work through the answer (neither) before introducing this phase as the piece that closes that exact gap.",
  concept: "Introduce SigMF as a genuinely useful, real-world open standard, not a course-specific invention — students may encounter it again professionally. Emphasize the interoperability angle: a capture made in this course's system can be opened and analyzed in completely unrelated external tools, because the format is a real, shared standard rather than a bespoke one.",
  designDecisions: "The three different native hardware formats (ci16_le for RX-888, cu8 for RTL-SDR, ci8 for HackRF) are a good concrete example of 'the same conceptual task requires different code for different hardware.' Have students work out on the board why an UNSIGNED 8-bit format (RTL-SDR) needs different math than a SIGNED 8-bit format (HackRF) before showing them the actual normalization code.",
  runningTheLab: "Have students actually inspect the resulting .sigmf-meta JSON file by hand after a real capture, not just trust that the script succeeded — reading real metadata (confirming frequency, sample rate, hash) reinforces that the file is a real, human-readable artifact, not an opaque binary blob.",
  gotchaStory: "Tell this one as a story about catching your OWN mistake before it ships, since that's a rarer and more valuable narrative than a bug found by a user. While writing this module, a specific library method name for setting author/description metadata was written into the code as if confirmed — but it had actually only been guessed by pattern-matching against how similar libraries tend to work. That guess was caught and explicitly flagged in the code's own comments BEFORE ever running against real hardware, with an honest note along the lines of 'this is unconfirmed, here is a safe fallback if it's wrong' rather than presenting false confidence. When a real hardware capture was finally run, the guess turned out to be correct — but make the point explicitly to students that the VALUE of the practice doesn't depend on the guess having been right. The discipline is flagging what's actually confirmed versus what's a reasonable-but-untested assumption, every time, regardless of how the coin happens to land. Ask: can students think of a time they presented something as fact in their own work that was actually still a guess?",
  discussion: [
    { q: "Why does an open standard like SigMF matter more for a SIGINT tool than a proprietary internal format would?", note: "An open standard means captures remain useful and analyzable even if THIS specific project's tooling becomes unavailable or unmaintained." },
    { q: "What's the practical cost of the 8-bit-to-complex64 conversion, and when would preserving native bit depth actually matter?", note: "The cost is up to 8x file size for very little analytical benefit in most cases — native bit depth matters most when storage/bandwidth is genuinely constrained, or extreme precision is required." },
    { q: "How do you decide when a claim in your own code is 'confirmed' versus 'a reasonable guess that hasn't been tested yet'?", note: "The honest answer: if you haven't run it against a real case and watched it succeed, it's a guess, no matter how confident it feels." }
  ],
  wrapUp: "Preview Phase 6.6 as bringing everything together — turning raw signal energy into structured, AI-queryable data, using a real amateur-radio tool (Kismet) as a design reference."
},
{
  id: "lab11",
  duration: "90 minutes",
  prerequisites: "Phase 6.5 completed; HackRF and/or RTL-SDR with a real antenna (ideally something more capable than a stock whip, if available).",
  opening: "Ask if anyone in class has used Kismet before, for WiFi/Bluetooth device tracking. If so, have them briefly describe how it tracks devices over time — this primes the whole session's core analogy before you introduce it formally.",
  concept: "The key conceptual challenge this session teaches is: RF signals, unlike WiFi devices, generally don't have a durable identity the way a MAC address gives a WiFi device. Spend real time on this — it's the single hardest idea in the session, and the frequency-binning solution (aggregating on frequency + mode as a substitute identity) only makes sense once students feel the actual problem it solves.",
  designDecisions: "Walk through the signals/sightings split as a direct, deliberate borrowing from Kismet's own DEVICES/PACKETS tables — but be precise with students that this is a DESIGN REFERENCE, not an interoperability requirement; nothing in this build needs to read or write Kismet's actual file format. The paired seconds+milliseconds timestamp convention is a nice concrete detail worth highlighting: it mirrors a genuinely old, proven C-level pattern (struct timeval's tv_sec/tv_usec split) rather than a single combined millisecond integer.",
  runningTheLab: "The calibration step is the most pedagogically important part of this lab — do not let students skip straight to a guessed threshold. Have them run --calibrate on a genuinely quiet frequency FIRST, and discuss what the reported numbers mean, before ever touching live detection.",
  gotchaStory: "This story is really about learning to distrust a suspiciously clean result, which is a rarer diagnostic skill than catching an outright error. During real threshold calibration, two separate runs — one at 10 MHz (HF) and one at 144.39 MHz (VHF), completely different bands — came back with essentially IDENTICAL noise-floor readings, down to a tenth of a decibel, with almost no statistical variance. On the surface, the tool ran successfully both times with no error. But a genuine off-air noise floor should differ meaningfully between two such different bands, and should show real spread over a 30-second window, not near-zero variance. That similarity WAS the actual diagnostic signal. The eventual explanation combined two real issues: calibrating directly on a continuous carrier (measuring signal, not background noise) in one case, and an antenna genuinely inadequate for the frequencies in question in another. Ask students directly: the tool never threw an error. How do you build the habit of distrusting a clean-looking number anyway, and what would you check first?",
  discussion: [
    { q: "Why doesn't a fixed-size frequency bin work equally well for a 125kHz LoRa channel and a 20MHz WiFi channel?", note: "A bin sized correctly for a narrow channel will incorrectly split a wide channel into many separate 'signals'; a bin sized for a wide channel will incorrectly merge multiple distinct narrow signals into one." },
    { q: "What real-world antenna or RF-path problem would produce two suspiciously identical noise-floor readings at very different frequencies?", note: "An antenna with no real gain at either frequency, or a fundamentally disconnected/faulty RF path, would both plausibly produce flat, low, undifferentiated readings regardless of actual band." },
    { q: "If you had to extend this schema to also track signal BANDWIDTH occupancy, not just center frequency, what would you add?", note: "Look for answers proposing a bandwidth range or occupied-spectrum field per sighting, not just a single center-frequency value." }
  ],
  wrapUp: "Tell students the final lab session brings the entire semester together into real, applied use cases, and previews the (not-yet-designed) final project they'll be assigned after it."
}
];
