// Teacher narrative content, sessions 1-4 (Intro, Phase 1, Phase 2, Phase 3)
module.exports = [
{
  id: "lab00",
  duration: "60-75 minutes",
  prerequisites: "None. This is the orientation session.",
  opening: "Open by asking the class two separate questions before connecting them: \"What does it mean for AI to be sovereign, rather than just local?\" and \"What is SIGINT, and who actually does it?\" Let a few answers surface before you supply the formal definitions. The connection you want them to reach on their own, or nearly so, is that this course is not about running a chatbot on a home server — it is about building an entire signals-intelligence capability that never has to send a single byte of RF data or query content to a third party. That distinction is the spine of the whole course.",
  concept: "Walk the architecture diagram left to right: hardware, then the AI stack, then the SIGINT-specific stack. Resist the urge to explain every phase in depth today — the point of this session is the shape of the system, not its details. Emphasize the \"local by default, cloud by exception\" phrase specifically; it is worth writing on the board. Make clear that cloud LLMs are not forbidden in this architecture, they are demoted to a deliberate, opt-in escalation path for non-sensitive queries, which is a meaningfully different posture than most students will have encountered in consumer AI products.",
  designDecisions: "Explain why the course is structured one lab per build phase, rather than a handful of broader labs. The reason is pedagogical as much as technical: every phase in the real build was independently validated before the next one was allowed to depend on it, and you want students internalizing that discipline from week one, not as an afterthought. Tell them plainly that every gotcha story they'll hear across the semester is real — pulled directly from an actual build log, not invented for teaching purposes. This tends to land well; students engage differently with a real failure than a hypothetical one.",
  runningTheLab: "This session's lab is light by design — reading comprehension and orientation, not hands-on building. Have students actually open docs/build-order.md themselves rather than just look at your slides; navigating the real repository is a skill in itself; and have them identify, honestly, which hardware they personally have access to (RX-888, HackRF, RTL-SDR, etc.), since that will determine which labs they can complete fully hands-on versus follow along conceptually. Surface that mismatch now rather than in week three.",
  gotchaStory: "There isn't a single bug story for this session — instead, use this time to set expectations for how failure stories will be told across the rest of the course. Tell students directly: every \"Real-World Bug\" slide in this course describes something that broke on real hardware, was diagnosed from the actual error message (not guessed), and was fixed in a way that was later confirmed to work. Frame this as modeling professional practice, not entertainment — the goal is that by the end of the semester, when THEIR build breaks, their instinct is to read the actual error rather than guess.",
  discussion: [
    { q: "What are the tradeoffs of sovereign/local AI versus a cloud API, for a security-sensitive organization?", note: "Push past \"cloud is less secure\" as an answer — ask what SPECIFIC data leaves the building in a cloud model (queries, embeddings, raw signal content) and what the actual exposure is for each." },
    { q: "Why might a course combine AI infrastructure with amateur radio/SIGINT skills specifically?", note: "A good answer touches on how RF monitoring generates exactly the kind of sensitive, high-volume, pattern-rich data that benefits most from local AI assistance — and exactly the kind you'd least want going to a third party." },
    { q: "What hardware constraints do you expect to hit first, given your own available equipment?", note: "Use this to identify students without RX-888 access early, so you can plan pairing/sharing for the HF-specific labs later in the semester." }
  ],
  wrapUp: "Close by previewing Phase 1 concretely: next session, students will install and validate real SDR hardware drivers, and will hit their first real, documented bug within the first lab. Tell them to bring whatever SDR hardware they personally have access to."
},
{
  id: "lab01",
  duration: "75-90 minutes",
  prerequisites: "At least one SDR device (RTL-SDR, HackRF, or RX-888) per student or pair; Ubuntu 24.04 environment.",
  opening: "Start with a provocation: \"Why should you trust that your SDR hardware works at all, before you've even opened an application to use it?\" Most students coming from a software background will not have thought about validating a hardware/driver layer in isolation before building on top of it — this is a genuinely different discipline than most software courses teach, and it's worth naming explicitly as the theme of today's session.",
  concept: "The centerpiece concept today is the RX-888 exception. Draw two columns on the board: one for HackRF/RTL-SDR (one shared driver library, every application links against it), one for RX-888 (no shared library, two entirely separate codebases each talking to raw USB). Make the point that this isn't a defect in the RX-888's design — it's a real, recognized pattern across several devices (USRP, bladeRF, LimeSDR), and understanding it now will make the Phase 6.1 lab, much later in the semester, click immediately instead of feeling like new information.",
  designDecisions: "Spend real time on WHY this build validates hardware standalone before any application touches it. Ask students to imagine debugging a failure three phases deep into the build, with no idea whether the actual USB link ever worked at all. That's the failure mode this phase's discipline prevents. It's a good moment to connect to their own prior coursework or work experience — has anyone debugged a system where they couldn't tell if the problem was hardware or software?",
  runningTheLab: "Watch closely during the reboot step — students WILL forget it, then wonder why usbfs_memory_mb hasn't changed. Use this as a live teaching moment if it happens rather than just reminding them in advance; a mistake made and then diagnosed sticks better than an instruction merely followed. Budget real time for the RX-888 build specifically if any students have that hardware — it compiles from source and takes noticeably longer than the packaged HackRF/RTL-SDR installs.",
  gotchaStory: "Tell this one as a two-part detective story, because it genuinely was one on the real build. Part one: 'apt install librtlsdr0' failed outright on a fresh Ubuntu 24.04 box — a package that should exist, didn't. The actual cause was a SONAME version bump; the package had been renamed librtlsdr2 in this specific Ubuntu release. Part two, discovered LATER in the same session: usbfs_memory_mb was set correctly, applied without error, and then silently reverted after a reboot — because this particular kernel builds usbcore in statically rather than as a loadable module, so the modprobe.d configuration file was just being ignored. The fix moved the setting into a GRUB kernel boot parameter instead, which works regardless of whether usbcore is a module or built in. Ask students: how would you have diagnosed the second bug, given that no error message appeared at all? The answer is checking the actual runtime value after reboot, not trusting that a config file having no error means it took effect.",
  discussion: [
    { q: "Why does a shared driver library create a different risk profile than a device-specific codebase like RX-888's?", note: "Steer toward: a shared library gets tested by every application using it, spreading out the discovery of bugs; a device-specific codebase's bugs are only found by that one codebase's own users." },
    { q: "What other embedded/IoT hardware have you seen with this same 'built statically vs. loadable module' kernel behavior?", note: "If no one has an example, mention that this exact ambiguity is common across embedded Linux generally, not unique to this build — worth normalizing as something to always verify, never assume." },
    { q: "How would you have caught the librtlsdr0/librtlsdr2 rename without running the actual install?", note: "Good answers include checking the distro's actual package index before writing the install script — but make the point that even that check can go stale by the time a student runs it a semester later." }
  ],
  wrapUp: "Preview Phase 2 as \"the boring but necessary session\" — rootless containers and a very long-running background process that looks broken but isn't. Tell students they'll need patience today, not cleverness."
},
{
  id: "lab02",
  duration: "60-75 minutes",
  prerequisites: "Phase 1 completed and validated.",
  opening: "Acknowledge directly that this is a less exciting session than Phase 1 or the ones to come — no antennas, no waterfalls. Frame it anyway as foundational: everything from Phase 3 onward depends on the venv strategy and container setup decided here. A weak opening for this specific session is pretending it's thrilling; a strong one is being honest that it's plumbing, and plumbing matters.",
  concept: "Introduce rootless Podman by contrasting it with the traditional root-daemon container model most students may have seen (Docker). Ask: what's the actual attack surface difference between a container escape that lands you as root on the host, versus one that lands you as an unprivileged user? This is a good moment to draw on any cybersecurity-adjacent material students have had elsewhere in their program.",
  designDecisions: "The venv-isolation decision (two separate, deliberately non-overlapping Python environments) is worth dwelling on, because its payoff doesn't arrive until Phase 6.2, several sessions from now. Tell students explicitly: \"You will not see why this matters today. You will see it in several weeks, when GNU Radio needs system Python and nothing in either venv can import it — and that will be by design, not an accident we're fixing later.\" Planting that forward reference now makes the later session land harder.",
  runningTheLab: "The FFTW background job is the operational centerpiece of this lab. Kick it off early in the session, then move on to the rest of Phase 2 while it runs in the background — do not have students sit and wait for it. It's designed to still be running when the session ends, and that's the correct outcome, not a failure to fix before dismissing class.",
  gotchaStory: "This is a story about a NON-bug that looks exactly like a bug — arguably a more valuable lesson than an actual failure. An hour into a real build, checking on FFTW's wisdom-generation file and finding nothing written yet is a genuinely alarming sight if you don't know what to expect. Walk students through the actual diagnostic: fftwf-wisdom only writes its output ONCE, at the very end of planning, and multi-million-point transform planning at default effort can take many hours. The correct check isn't \"does the output file exist,\" it's \"is the process alive and consuming CPU\" (ps aux | grep fftwf-wisdom). Make the broader point explicit: not every quiet process is a dead one, and knowing the difference is a real, transferable operations skill.",
  discussion: [
    { q: "What are the security tradeoffs of rootless versus rootful containers in a production environment?", note: "Push toward specifics: what CAN'T a rootless container do that a rootful one can, and is that a limitation or a feature for this build's actual use case?" },
    { q: "Why deliberately avoid --system-site-packages even though it would make some later steps simpler?", note: "The right answer centers on dependency isolation — avoiding a future conflict between GNU Radio's system bindings and this build's own pinned package versions." },
    { q: "When should a long-running background job worry you, versus when is 'it's just slow' the right diagnosis?", note: "Good answers reference checking for actual activity (CPU/process state) rather than just elapsed time or the presence/absence of output." }
  ],
  wrapUp: "Tell students Phase 3 is where the AI stack actually starts — and that it includes the first REAL, multi-layered debugging session of the course, spanning both networking and file permissions at once."
},
{
  id: "lab03",
  duration: "75-90 minutes",
  prerequisites: "Phase 2 completed and validated; NVIDIA GPU recommended for full inference speed.",
  opening: "Open with a live demonstration if your hardware allows it: run a query against the freshly installed model and let students watch GPU utilization spike in nvidia-smi in a second terminal. Concrete, visible proof that local inference is actually happening tends to land better than describing it.",
  concept: "Explain the three-model lineup (qwen3:14b, nomic-embed-text, gemma3:12b) not as an arbitrary list but as three DIFFERENT jobs: general reasoning, RAG embeddings, and vision. Ask students what a fourth model might be needed for, later in the course, to prime them for thinking about model selection as task-driven rather than \"pick the biggest one.\"",
  designDecisions: "Spend real time on the native-versus-containerized decision. It's a good moment to discuss GPU passthrough complexity in general — ask if anyone has tried to get GPU access working inside a Docker container before, and what that involved. Most students who have will have war stories of their own to share.",
  runningTheLab: "This lab has real GPU download time built in (17GB+ of model weights) — start the pull as close to the beginning of class as logistics allow, and use the wait productively rather than having it eat into hands-on time later.",
  gotchaStory: "This is the best multi-layered debugging story in the early part of the course, and it deserves real time. Set the scene: on the actual build, Open WebUI (installed next session, but assume it exists for the story) could not reach Ollama's API at all. The FIRST fix was straightforward once diagnosed — Ollama defaults to binding 127.0.0.1 only, invisible from a separate container network namespace, fixed with OLLAMA_HOST=0.0.0.0. But here's the twist: that fix alone wasn't enough. Ollama then failed to even START, with 'permission denied' trying to write to /data/models — despite /data/models itself already being correctly chowned to the ollama user. The actual root cause was one level up: the PARENT directory, /data, was locked down to the human operator's own group, and the ollama system user wasn't a member of it — so it couldn't even traverse INTO /data to reach the child directory it did own. Ask students directly: why doesn't owning a child directory guarantee you can reach it? This is a genuinely subtle Unix permissions lesson (execute permission on a directory means 'traverse,' not 'list' or 'read') that a surprising number of working engineers get wrong.",
  discussion: [
    { q: "Why does chowning a subdirectory not guarantee a service can reach it?", note: "Make sure the traverse-versus-read/write distinction on directory permissions gets stated explicitly, not just implied." },
    { q: "Given the LAN-exposure tradeoff of OLLAMA_HOST=0.0.0.0, what firewall rule would you add in a real deployment?", note: "Look for answers scoping access to specific source IPs/subnets rather than a blanket allow, and awareness that Ollama itself has no built-in authentication." },
    { q: "What's the difference between a 'the service won't start' bug and a 'the service starts but can't be reached' bug, and how does your diagnostic approach differ?", note: "Good answers separate service-log diagnosis (journalctl) from network-reachability diagnosis (curl, netstat) as genuinely different toolkits." }
  ],
  wrapUp: "Preview Phase 4 as where the actual user-facing interface goes live — and warn students, with a slight smile, that it contains not one but THREE real, distinct bugs discovered in sequence on the real build."
}
];
