#!/usr/bin/env bash
# scripts/phase4-open-webui.sh
#
# Phase 4 — Open WebUI (Podman container), fronted by Caddy. See
# docs/build-order.md for full rationale.
#
# Deploys rootless — Quadlet units go under
# ~/.config/containers/systemd/, managed by `systemctl --user`. Run this
# as your normal user, NOT with sudo (Phase 2 already set up the
# subuid/subgid range and lingering this needs).
#
# This script INSTALLS. Run scripts/phase4-validate.sh afterward.
#
# Usage: ./scripts/phase4-open-webui.sh

set -euo pipefail

if [[ "$(id -u)" -eq 0 ]]; then
  echo "Do not run this as root/sudo — rootless Quadlet units need to be" >&2
  echo "owned by and run as your normal user. Re-run without sudo." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
QUADLET_DIR="${HOME}/.config/containers/systemd"

echo "== Phase 4: Open WebUI + Caddy =="

mkdir -p "${QUADLET_DIR}"

echo "-- Installing Quadlet units and Caddyfile to ${QUADLET_DIR} --"
cp "${REPO_ROOT}/containers/open-webui.container" "${QUADLET_DIR}/"
cp "${REPO_ROOT}/containers/caddy.container" "${QUADLET_DIR}/"

# Caddyfile: plain HTTP by default, local-CA HTTPS opt-in via CADDY_TLS=1.
#   CADDY_TLS=1 ./scripts/phase4-open-webui.sh    → local-CA HTTPS on :8443
#   CADDY_TLS=cert CADDY_CERT=/path/fullchain.pem CADDY_KEY=/path/key.pem \
#     CADDY_HOSTNAME=host.example.com ./scripts/phase4-open-webui.sh
#                                                 → HTTPS on :8443 with YOUR cert
#   ./scripts/phase4-open-webui.sh                → HTTP on :8000 (default)
#
# HTTP is the default deliberately: for a single-operator box on a
# trusted LAN with no DNS, plain HTTP is a legitimate, simpler choice,
# and the TLS path carries real caveats (client-side CA trust, hostname
# resolution without DNS) documented in docs/security-hardening.md.
#
# CADDY_TLS=cert is for operators who ALREADY have a certificate — from
# an internal/corporate CA, an existing wildcard, or their own PKI — and
# want to use it instead of Caddy's self-signed local CA. The advantage:
# if that cert chains to a CA the clients ALREADY trust (e.g. a corporate
# root pushed to every machine), there's no per-client trust step at all.
if [[ "${CADDY_TLS:-0}" == "cert" ]]; then
  # Bring-your-own-certificate mode.
  : "${CADDY_CERT:?CADDY_TLS=cert requires CADDY_CERT=/path/to/fullchain.pem}"
  : "${CADDY_KEY:?CADDY_TLS=cert requires CADDY_KEY=/path/to/privkey.pem}"
  CADDY_HOST="${CADDY_HOSTNAME:-$(hostname).local}"

  if [[ ! -r "${CADDY_CERT}" ]]; then
    echo "ERROR: cert file not readable: ${CADDY_CERT}" >&2; exit 1
  fi
  if [[ ! -r "${CADDY_KEY}" ]]; then
    echo "ERROR: key file not readable: ${CADDY_KEY}" >&2; exit 1
  fi

  echo "   CADDY_TLS=cert — using your certificate for ${CADDY_HOST}:8443"
  # Copy the cert/key into a stable location the container mounts, rather
  # than mounting the user's arbitrary source paths directly (which may
  # live somewhere the rootless container can't traverse). 0600 key.
  CERT_DIR="${HOME}/.config/containers/systemd/caddy-certs"
  mkdir -p "${CERT_DIR}"
  cp "${CADDY_CERT}" "${CERT_DIR}/cert.pem"
  cp "${CADDY_KEY}"  "${CERT_DIR}/key.pem"
  chmod 0600 "${CERT_DIR}/key.pem"
  chmod 0644 "${CERT_DIR}/cert.pem"

  # Ensure the container mounts the cert dir. Add the Volume line to the
  # unit if not already present (idempotent).
  if ! grep -q "caddy-certs:/etc/caddy/certs" "${QUADLET_DIR}/caddy.container"; then
    # Insert the mount right after the Caddyfile volume line.
    sed -i '/Volume=%h\/.config\/containers\/systemd\/Caddyfile/a Volume=%h/.config/containers/systemd/caddy-certs:/etc/caddy/certs:ro' \
      "${QUADLET_DIR}/caddy.container"
  fi

  # auto_https disable_redirects still required (same :80-bind reason as
  # the local-CA path — Caddy auto-opens :80 for the redirect otherwise).
  cat > "${QUADLET_DIR}/Caddyfile" <<EOF
# Caddyfile — sovereign-sigint (operator-provided cert, generated by phase4)
{
	auto_https disable_redirects
}

${CADDY_HOST}:8443 {
	tls /etc/caddy/certs/cert.pem /etc/caddy/certs/key.pem
	reverse_proxy 127.0.0.1:8080
}
EOF
  echo "   NOTE: clients reach this at https://${CADDY_HOST}:8443"
  echo "   If ${CADDY_HOST} isn't in DNS, ensure clients can resolve it"
  echo "   (hosts file or DNS). No per-client CA trust step is needed IF"
  echo "   your cert chains to a CA the clients already trust."
elif [[ "${CADDY_TLS:-0}" == "1" ]]; then
  CADDY_HOST="$(hostname).local"
  echo "   CADDY_TLS=1 set — generating local-CA HTTPS config for ${CADDY_HOST}:8443"
  # The global 'auto_https disable_redirects' block is REQUIRED, not
  # optional: 'tls internal' otherwise makes Caddy auto-open privileged
  # :80 for the HTTP->HTTPS redirect, which rootless Podman cannot bind
  # ("listening on :80: bind: permission denied"), crashing Caddy on
  # startup despite the site block being :8443. This was a real,
  # diagnosed bug — do not remove this block.
  cat > "${QUADLET_DIR}/Caddyfile" <<EOF
# Caddyfile — sovereign-sigint (local-CA HTTPS, generated by phase4)
{
	auto_https disable_redirects
}

${CADDY_HOST}:8443 {
	tls internal
	reverse_proxy 127.0.0.1:8080
}
EOF
  echo "   NOTE: clients reach this at https://${CADDY_HOST}:8443"
  echo "   Without DNS, add '<this-box-ip> ${CADDY_HOST}' to each client's"
  echo "   hosts file, and trust Caddy's local CA to avoid browser warnings"
  echo "   (extraction steps in docs/security-hardening.md)."
else
  echo "   Plain HTTP on :8000 (default; set CADDY_TLS=1 for local-CA HTTPS)"
  cp "${REPO_ROOT}/containers/Caddyfile" "${QUADLET_DIR}/"
fi

# Sanity check: /data/rag must exist and be writable before Open WebUI
# starts, or the bind mount in open-webui.container fails outright.
if [[ ! -d /data/rag ]]; then
  echo "ERROR: /data/rag does not exist. Run scripts/setup-data-dirs.sh first." >&2
  exit 1
fi

echo "-- Reloading systemd user units --"
systemctl --user daemon-reload

echo "-- Starting Open WebUI and Caddy --"
# Quadlet-generated units are transient/generator-produced — systemctl
# enable fails on them ("is transient or generated"), confirmed via a
# real install. Enablement already happened automatically at generation
# time via each .container file's own [Install] section
# (WantedBy=default.target) — just start them.
systemctl --user start open-webui.service
systemctl --user start caddy.service

echo "Waiting for Open WebUI to come up..."
for i in $(seq 1 30); do
  if curl -fsS http://127.0.0.1:8080/ >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

echo
echo "== Phase 4 install complete =="
echo
echo "Next: run scripts/phase4-validate.sh to confirm Open WebUI is actually"
echo "reachable (direct and via Caddy) and can talk to Ollama."
echo

# Reflect the DEPLOYED Caddyfile's actual state (in QUADLET_DIR), not the
# repo copy — the TLS paths generate their config directly to the deployed
# location, so checking the repo file would misreport when TLS is on.
# NOTE: strip comment lines before matching — the plain-HTTP Caddyfile ships a
# commented example containing "tls internal", and matching that would wrongly
# print the HTTPS message even though the active config is plain :8000.
DEPLOYED_ACTIVE="$(grep -v '^[[:space:]]*#' "${QUADLET_DIR}/Caddyfile" 2>/dev/null)"
if echo "${DEPLOYED_ACTIVE}" | grep -q "tls /etc/caddy/certs"; then
  echo "Caddy is configured for HTTPS on :8443 using your provided certificate."
  echo "No per-client CA trust step is needed if that cert chains to a CA"
  echo "your clients already trust; otherwise trust its issuing CA per client."
elif echo "${DEPLOYED_ACTIVE}" | grep -q "tls internal"; then
  echo "Caddy is configured for HTTPS via local CA on :8443."
  echo "Browsers will warn until the local root CA is trusted on each client —"
  echo "see docs/security-hardening.md for the extraction and trust steps."
else
  echo "Reminder: Caddy is on plain HTTP (:8000) by default — not :80, since"
  echo "rootless Podman can't bind privileged ports without a system-wide"
  echo "policy change (confirmed via a real install) — see"
  echo "containers/Caddyfile for how to add HTTPS if/when this needs it."
fi
